export const COUNTRY_CODE_SELECT_OPTIONS = [
  // Top options, often displayed separately for quick access
  { value: "44", label: "UK (+44)", countryCode: "GB", selected: true }, 
  { value: "1", label: "USA (+1)", countryCode: "US" },
  { value: "91", label: "India (+91)", countryCode: "IN" }, 

  {
    group: "Other countries",
    options: [
      { value: "213", label: "Algeria (+213)", countryCode: "DZ" },
      { value: "376", label: "Andorra (+376)", countryCode: "AD" },
      { value: "244", label: "Angola (+244)", countryCode: "AO" },
      { value: "1264", label: "Anguilla (+1264)", countryCode: "AI" },
      { value: "1268", label: "Antigua & Barbuda (+1268)", countryCode: "AG" },
      { value: "54", label: "Argentina (+54)", countryCode: "AR" },
      { value: "374", label: "Armenia (+374)", countryCode: "AM" },
      { value: "297", label: "Aruba (+297)", countryCode: "AW" },
      { value: "61", label: "Australia (+61)", countryCode: "AU" },
      { value: "43", label: "Austria (+43)", countryCode: "AT" },
      { value: "994", label: "Azerbaijan (+994)", countryCode: "AZ" },
      { value: "1242", label: "Bahamas (+1242)", countryCode: "BS" },
      { value: "973", label: "Bahrain (+973)", countryCode: "BH" },
      { value: "880", label: "Bangladesh (+880)", countryCode: "BD" },
      { value: "1246", label: "Barbados (+1246)", countryCode: "BB" },
      { value: "375", label: "Belarus (+375)", countryCode: "BY" },
      { value: "32", label: "Belgium (+32)", countryCode: "BE" },
      { value: "501", label: "Belize (+501)", countryCode: "BZ" },
      { value: "229", label: "Benin (+229)", countryCode: "BJ" },
      { value: "1441", label: "Bermuda (+1441)", countryCode: "BM" },
      { value: "975", label: "Bhutan (+975)", countryCode: "BT" },
      { value: "591", label: "Bolivia (+591)", countryCode: "BO" },
      { value: "387", label: "Bosnia Herzegovina (+387)", countryCode: "BA" },
      { value: "267", label: "Botswana (+267)", countryCode: "BW" },
      { value: "55", label: "Brazil (+55)", countryCode: "BR" },
      { value: "673", label: "Brunei (+673)", countryCode: "BN" },
      { value: "359", label: "Bulgaria (+359)", countryCode: "BG" },
      { value: "226", label: "Burkina Faso (+226)", countryCode: "BF" },
      { value: "257", label: "Burundi (+257)", countryCode: "BI" },
      { value: "855", label: "Cambodia (+855)", countryCode: "KH" },
      { value: "237", label: "Cameroon (+237)", countryCode: "CM" },
      { value: "1", label: "Canada (+1)", countryCode: "CA" }, // Canada also uses +1
      { value: "238", label: "Cape Verde Islands (+238)", countryCode: "CV" },
      { value: "1345", label: "Cayman Islands (+1345)", countryCode: "KY" },
      {
        value: "236",
        label: "Central African Republic (+236)",
        countryCode: "CF",
      },
      { value: "56", label: "Chile (+56)", countryCode: "CL" },
      { value: "86", label: "China (+86)", countryCode: "CN" },
      { value: "57", label: "Colombia (+57)", countryCode: "CO" },
      { value: "269", label: "Comoros (+269)", countryCode: "KM" },
      { value: "242", label: "Congo (+242)", countryCode: "CG" },
      { value: "682", label: "Cook Islands (+682)", countryCode: "CK" },
      { value: "506", label: "Costa Rica (+506)", countryCode: "CR" },
      { value: "385", label: "Croatia (+385)", countryCode: "HR" },
      { value: "53", label: "Cuba (+53)", countryCode: "CU" },
      { value: "90392", label: "Cyprus North (+90392)", countryCode: "CY" }, // Note: You might want to consolidate Cyprus
      { value: "357", label: "Cyprus South (+357)", countryCode: "CY" },
      { value: "42", label: "Czech Republic (+42)", countryCode: "CZ" },
      { value: "45", label: "Denmark (+45)", countryCode: "DK" },
      { value: "253", label: "Djibouti (+253)", countryCode: "DJ" },
      { value: "1809", label: "Dominica (+1809)", countryCode: "DM" },
      { value: "1809", label: "Dominican Republic (+1809)", countryCode: "DO" },
      { value: "593", label: "Ecuador (+593)", countryCode: "EC" },
      { value: "20", label: "Egypt (+20)", countryCode: "EG" },
      { value: "503", label: "El Salvador (+503)", countryCode: "SV" },
      { value: "240", label: "Equatorial Guinea (+240)", countryCode: "GQ" },
      { value: "291", label: "Eritrea (+291)", countryCode: "ER" },
      { value: "372", label: "Estonia (+372)", countryCode: "EE" },
      { value: "251", label: "Ethiopia (+251)", countryCode: "ET" },
      { value: "500", label: "Falkland Islands (+500)", countryCode: "FK" },
      { value: "298", label: "Faroe Islands (+298)", countryCode: "FO" },
      { value: "679", label: "Fiji (+679)", countryCode: "FJ" },
      { value: "358", label: "Finland (+358)", countryCode: "FI" },
      { value: "33", label: "France (+33)", countryCode: "FR" },
      { value: "594", label: "French Guiana (+594)", countryCode: "GF" },
      { value: "689", label: "French Polynesia (+689)", countryCode: "PF" },
      { value: "241", label: "Gabon (+241)", countryCode: "GA" },
      { value: "220", label: "Gambia (+220)", countryCode: "GM" },
      { value: "7880", label: "Georgia (+7880)", countryCode: "GE" },
      { value: "49", label: "Germany (+49)", countryCode: "DE" },
      { value: "233", label: "Ghana (+233)", countryCode: "GH" },
      { value: "350", label: "Gibraltar (+350)", countryCode: "GI" },
      { value: "30", label: "Greece (+30)", countryCode: "GR" },
      { value: "299", label: "Greenland (+299)", countryCode: "GL" },
      { value: "1473", label: "Grenada (+1473)", countryCode: "GD" },
      { value: "590", label: "Guadeloupe (+590)", countryCode: "GP" },
      { value: "671", label: "Guam (+671)", countryCode: "GU" },
      { value: "502", label: "Guatemala (+502)", countryCode: "GT" },
      { value: "224", label: "Guinea (+224)", countryCode: "GN" },
      { value: "245", label: "Guinea - Bissau (+245)", countryCode: "GW" },
      { value: "592", label: "Guyana (+592)", countryCode: "GY" },
      { value: "509", label: "Haiti (+509)", countryCode: "HT" },
      { value: "504", label: "Honduras (+504)", countryCode: "HN" },
      { value: "852", label: "Hong Kong (+852)", countryCode: "HK" },
      { value: "36", label: "Hungary (+36)", countryCode: "HU" },
      { value: "354", label: "Iceland (+354)", countryCode: "IS" },
      // { value: "91", label: "India (+91)", countryCode: "IN" }, // Moved to top
      { value: "62", label: "Indonesia (+62)", countryCode: "ID" },
      { value: "98", label: "Iran (+98)", countryCode: "IR" },
      { value: "964", label: "Iraq (+964)", countryCode: "IQ" },
      { value: "353", label: "Ireland (+353)", countryCode: "IE" },
      { value: "972", label: "Israel (+972)", countryCode: "IL" },
      { value: "39", label: "Italy (+39)", countryCode: "IT" },
      { value: "1876", label: "Jamaica (+1876)", countryCode: "JM" },
      { value: "81", label: "Japan (+81)", countryCode: "JP" },
      { value: "962", label: "Jordan (+962)", countryCode: "JO" },
      { value: "7", label: "Kazakhstan (+7)", countryCode: "KZ" },
      { value: "254", label: "Kenya (+254)", countryCode: "KE" },
      { value: "686", label: "Kiribati (+686)", countryCode: "KI" },
      { value: "850", label: "Korea North (+850)", countryCode: "KP" },
      { value: "82", label: "Korea South (+82)", countryCode: "KR" },
      { value: "965", label: "Kuwait (+965)", countryCode: "KW" },
      { value: "996", label: "Kyrgyzstan (+996)", countryCode: "KG" },
      { value: "856", label: "Laos (+856)", countryCode: "LA" },
      { value: "371", label: "Latvia (+371)", countryCode: "LV" },
      { value: "961", label: "Lebanon (+961)", countryCode: "LB" },
      { value: "266", label: "Lesotho (+266)", countryCode: "LS" },
      { value: "231", label: "Liberia (+231)", countryCode: "LR" },
      { value: "218", label: "Libya (+218)", countryCode: "LY" },
      { value: "417", label: "Liechtenstein (+417)", countryCode: "LI" },
      { value: "370", label: "Lithuania (+370)", countryCode: "LT" },
      { value: "352", label: "Luxembourg (+352)", countryCode: "LU" },
      { value: "853", label: "Macao (+853)", countryCode: "MO" },
      { value: "389", label: "Macedonia (+389)", countryCode: "MK" },
      { value: "261", label: "Madagascar (+261)", countryCode: "MG" },
      { value: "265", label: "Malawi (+265)", countryCode: "MW" },
      { value: "60", label: "Malaysia (+60)", countryCode: "MY" },
      { value: "960", label: "Maldives (+960)", countryCode: "MV" },
      { value: "223", label: "Mali (+223)", countryCode: "ML" },
      { value: "356", label: "Malta (+356)", countryCode: "MT" },
      { value: "692", label: "Marshall Islands (+692)", countryCode: "MH" },
      { value: "596", label: "Martinique (+596)", countryCode: "MQ" },
      { value: "222", label: "Mauritania (+222)", countryCode: "MR" },
      { value: "269", label: "Mayotte (+269)", countryCode: "YT" },
      { value: "52", label: "Mexico (+52)", countryCode: "MX" },
      { value: "691", label: "Micronesia (+691)", countryCode: "FM" },
      { value: "373", label: "Moldova (+373)", countryCode: "MD" },
      { value: "377", label: "Monaco (+377)", countryCode: "MC" },
      { value: "976", label: "Mongolia (+976)", countryCode: "MN" },
      { value: "1664", label: "Montserrat (+1664)", countryCode: "MS" },
      { value: "212", label: "Morocco (+212)", countryCode: "MA" },
      { value: "258", label: "Mozambique (+258)", countryCode: "MZ" },
      { value: "95", label: "Myanmar (+95)", countryCode: "MM" }, // Changed from MN to MM
      { value: "264", label: "Namibia (+264)", countryCode: "NA" },
      { value: "674", label: "Nauru (+674)", countryCode: "NR" },
      { value: "977", label: "Nepal (+977)", countryCode: "NP" },
      { value: "31", label: "Netherlands (+31)", countryCode: "NL" },
      { value: "687", label: "New Caledonia (+687)", countryCode: "NC" },
      { value: "64", label: "New Zealand (+64)", countryCode: "NZ" },
      { value: "505", label: "Nicaragua (+505)", countryCode: "NI" },
      { value: "227", label: "Niger (+227)", countryCode: "NE" },
      { value: "234", label: "Nigeria (+234)", countryCode: "NG" },
      { value: "683", label: "Niue (+683)", countryCode: "NU" },
      { value: "672", label: "Norfolk Islands (+672)", countryCode: "NF" },
      { value: "670", label: "Northern Marianas (+670)", countryCode: "MP" }, // Changed from NP to MP
      { value: "47", label: "Norway (+47)", countryCode: "NO" },
      { value: "968", label: "Oman (+968)", countryCode: "OM" },
      { value: "680", label: "Palau (+680)", countryCode: "PW" },
      { value: "507", label: "Panama (+507)", countryCode: "PA" },
      { value: "675", label: "Papua New Guinea (+675)", countryCode: "PG" },
      { value: "595", label: "Paraguay (+595)", countryCode: "PY" },
      { value: "51", label: "Peru (+51)", countryCode: "PE" },
      { value: "63", label: "Philippines (+63)", countryCode: "PH" },
      { value: "48", label: "Poland (+48)", countryCode: "PL" },
      { value: "351", label: "Portugal (+351)", countryCode: "PT" },
      { value: "1787", label: "Puerto Rico (+1787)", countryCode: "PR" },
      { value: "974", label: "Qatar (+974)", countryCode: "QA" },
      { value: "262", label: "Reunion (+262)", countryCode: "RE" },
      { value: "40", label: "Romania (+40)", countryCode: "RO" },
      { value: "7", label: "Russia (+7)", countryCode: "RU" },
      { value: "250", label: "Rwanda (+250)", countryCode: "RW" },
      { value: "378", label: "San Marino (+378)", countryCode: "SM" },
      { value: "239", label: "Sao Tome & Principe (+239)", countryCode: "ST" },
      { value: "966", label: "Saudi Arabia (+966)", countryCode: "SA" },
      { value: "221", label: "Senegal (+221)", countryCode: "SN" },
      { value: "381", label: "Serbia (+381)", countryCode: "RS" }, // Changed from CS to RS
      { value: "248", label: "Seychelles (+248)", countryCode: "SC" },
      { value: "232", label: "Sierra Leone (+232)", countryCode: "SL" },
      { value: "65", label: "Singapore (+65)", countryCode: "SG" },
      { value: "421", label: "Slovak Republic (+421)", countryCode: "SK" },
      { value: "386", label: "Slovenia (+386)", countryCode: "SI" },
      { value: "677", label: "Solomon Islands (+677)", countryCode: "SB" },
      { value: "252", label: "Somalia (+252)", countryCode: "SO" },
      { value: "27", label: "South Africa (+27)", countryCode: "ZA" },
      { value: "34", label: "Spain (+34)", countryCode: "ES" },
      { value: "94", label: "Sri Lanka (+94)", countryCode: "LK" },
      { value: "290", label: "St. Helena (+290)", countryCode: "SH" },
      { value: "1869", label: "St. Kitts (+1869)", countryCode: "KN" },
      { value: "1758", label: "St. Lucia (+1758)", countryCode: "LC" },
      { value: "249", label: "Sudan (+249)", countryCode: "SD" },
      { value: "597", label: "Suriname (+597)", countryCode: "SR" },
      { value: "268", label: "Swaziland (+268)", countryCode: "SZ" },
      { value: "46", label: "Sweden (+46)", countryCode: "SE" },
      { value: "41", label: "Switzerland (+41)", countryCode: "CH" },
      { value: "963", label: "Syria (+963)", countryCode: "SY" },
      { value: "886", label: "Taiwan (+886)", countryCode: "TW" },
      { value: "7", label: "Tajikstan (+7)", countryCode: "TJ" }, // Russia also uses +7
      { value: "66", label: "Thailand (+66)", countryCode: "TH" },
      { value: "228", label: "Togo (+228)", countryCode: "TG" },
      { value: "676", label: "Tonga (+676)", countryCode: "TO" },
      { value: "1868", label: "Trinidad & Tobago (+1868)", countryCode: "TT" },
      { value: "216", label: "Tunisia (+216)", countryCode: "TN" },
      { value: "90", label: "Turkey (+90)", countryCode: "TR" },
      { value: "7", label: "Turkmenistan (+7)", countryCode: "TM" }, // Russia also uses +7
      { value: "993", label: "Turkmenistan (+993)", countryCode: "TM" }, // Duplicate, check source
      {
        value: "1649",
        label: "Turks & Caicos Islands (+1649)",
        countryCode: "TC",
      },
      { value: "688", label: "Tuvalu (+688)", countryCode: "TV" },
      { value: "256", label: "Uganda (+256)", countryCode: "UG" },
      { value: "380", label: "Ukraine (+380)", countryCode: "UA" },
      { value: "971", label: "United Arab Emirates (+971)", countryCode: "AE" },
      { value: "598", label: "Uruguay (+598)", countryCode: "UY" },
      { value: "7", label: "Uzbekistan (+7)", countryCode: "UZ" }, // Russia also uses +7
      { value: "678", label: "Vanuatu (+678)", countryCode: "VU" },
      { value: "379", label: "Vatican City (+379)", countryCode: "VA" },
      { value: "58", label: "Venezuela (+58)", countryCode: "VE" },
      { value: "84", label: "Vietnam (+84)", countryCode: "VN" },
      {
        value: "1284",
        label: "Virgin Islands - British (+1284)",
        countryCode: "VG",
      }, // Changed from 84
      {
        value: "1340",
        label: "Virgin Islands - US (+1340)",
        countryCode: "VI",
      }, // Changed from 84
      { value: "681", label: "Wallis & Futuna (+681)", countryCode: "WF" },
      { value: "969", label: "Yemen (North)(+969)", countryCode: "YE" },
      { value: "967", label: "Yemen (South)(+967)", countryCode: "YE" },
      { value: "260", label: "Zambia (+260)", countryCode: "ZM" },
      { value: "263", label: "Zimbabwe (+263)", countryCode: "ZW" },
    ],
  },
];
